### PR TITLE
72 menu table view

### PR DESCRIPTION
**Pull request by TheSlat**
Fixes #72 - CreateTableModel class

please code review as I am new to SQL :eyes: 

:penguin: Ethan :bird:

### CODE REVIEW

**Comment by ozyx** [comment]
Needs to set header labels for the 0th column which is 'id'. 
Columns are id, name, price respectively. Other than that, looks great.

**Comment by TheSlat** [comment]
I hid the 0th column, still needs name?

**Comment by TheSlat** [comment]
Fixed. I think we need to add location ID to the view for the restaurant list though, cause right now I am just taking the row number and adding one to create the filter for menu, but if in the future the "foodie" can sort or otherwise re-order the list of locations that logic will break

**Comment by ozyx** [comment]
Ok I'll fix that today

**Comment by TheSlat** [comment]
cool man, if its a quick fix after that Ill do it but I have to try to get on my math HW till monday...

**Comment by ozyx** [comment]
Should be easy  ! Do your math hw 👌

**Comment by dank-developer** [comment]
yea do your math HW, I think we're in pretty good shape.

**Comment by ozyx** [comment]
running into a problem, there is some logic involving viewAllRestaurants_tableView and qt doesn't detect it, so it won't compile. I don't want to edit a bunch of stuff, anybody know what's up with this?

**Comment by ozyx** [comment]
i commented it all out. so we can worry about it after the UI has been completely implemented... we need to get that finished asap

**Comment by TheSlat** [comment]
everything compiles and works now, compatable with latest gui from develop branch. should merge, much good.

**Comment by ozyx** [comment]
Works!

**Comment by dank-developer** [comment]
We need to add in the dollar sign for cost and 'Miles' as a unit for the distance. #75

**Comment by ozyx** [comment]
Agreed, we can do that in the view itself

**Pull request merged**
